### ISSUE TITLE
Score.ended_at should be not be Optional[]

### ISSUE THREAD

**Issue by Syriiin** [tybug/ossapi#86]
According to the [`x-api-version >= 20220705` docs](https://osu.ppy.sh/docs/index.html#score) and a quick check of the [table schema](https://github.com/ppy/osu-web/blob/0a7736c5c059b76f088c6bfe68a8bde8f668739d/database/migrations/2024_01_12_115738_update_scores_table_final.php#L40) it seems `Score.ended_at` should be simply a `Datetime`.

Haven't done a thorough check of osu-web so I might be mistaken, but it also intuitively makes sense, since all scores have an associated date.

**Comment by tybug** [comment]
This makes me pretty nervous, because the api docs have been consistently wrong about the nullability of attributes, and I tend to just ignore them in favor of empirical testing nowadays. That said, the migration is strong evidence for this. I think it's likely I was overzealous for this particular type. Thanks!
